steps:
  # STEP 1: Fetch .env from Secret Manager
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'create-env-from-secret'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Fetching .env from Secret Manager..."
        gcloud secrets versions access latest --secret=env > .env

  # STEP 2: Prepare Docker --build-arg from .env
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'prepare-build-args'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ ! -f .env ]; then
          echo ".env file not found!"
          exit 1
        fi
        BUILD_ARGS=""
        while IFS= read -r line || [ -n "$line" ]; do
          if [[ ! "$line" =~ ^# && "$line" =~ .*=.* ]]; then
            key=$(echo "$line" | cut -d '=' -f 1)
            value=$(echo "$line" | cut -d '=' -f 2-)
            BUILD_ARGS+="--build-arg $key=$value "
          fi
        done < .env
        echo "$BUILD_ARGS" > build_args.txt

  # STEP 3: Build Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend-image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        BUILD_ARGS=$(cat build_args.txt)
        docker build $BUILD_ARGS -t asia-southeast2-docker.pkg.dev/tubesabp-459213/cloud-run-source-deploy/tubesabp/backend-api:$COMMIT_SHA -f tesbackend/Dockerfile tesbackend

  # STEP 4: Push Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-backend-image'
    args:
      - push
      - asia-southeast2-docker.pkg.dev/tubesabp-459213/cloud-run-source-deploy/tubesabp/backend-api:$COMMIT_SHA

  # STEP 5: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'deploy'
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - backend-api
      - '--platform=managed'
      - --image=asia-southeast2-docker.pkg.dev/tubesabp-459213/cloud-run-source-deploy/tubesabp/backend-api:$COMMIT_SHA
      - --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=ae167d95-618f-449c-a3d9-4b378da0514a
      - --region=asia-southeast2
      - --quiet

images:
  - asia-southeast2-docker.pkg.dev/tubesabp-459213/cloud-run-source-deploy/tubesabp/backend-api:$COMMIT_SHA

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _AR_PROJECT_ID: tubesabp-459213
  _PLATFORM: managed
  _SERVICE_NAME: backend-api
  _TRIGGER_ID: ae167d95-618f-449c-a3d9-4b378da0514a
  REPO_NAME: tubesabp
  _DEPLOY_REGION: asia-southeast2
  _AR_HOSTNAME: asia-southeast2-docker.pkg.dev
  _AR_REPOSITORY: cloud-run-source-deploy

tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - backend-api
